spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/omnidoc
spring.datasource.username=postgres
spring.datasource.password=hesoyam
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

minio.host=localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=omnidoc