spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/omnidoc
spring.datasource.username=postgres
spring.datasource.password=hesoyam
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

minio.host=localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=omnidoc


spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.cache.type=redis

spring.cache.redis.time-to-live=600000

spring.cache.redis.cache-null-values=false

spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=myapp