spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/testt
spring.datasource.username=postgres
spring.datasource.password=hesoyam
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect